### ISSUE TITLE
Needs syntax highlighting

### ISSUE THREAD

**Issue by morgandixon** [invisible-college/emo#1]
This requires representing the highlights somehow. This could either be:
- intervals that store the styling metadata
- nodes in the render tree

**Comment by toomim** [comment]
A hierarchy?

**Comment by morgandixon** [comment]
Edited my comment cuz it was confusing.

**Comment by toomim** [comment]
All editors I've used in the past keep a set of regions for styling metadata. One advantage of regions is that they can overlap in arbitrary ways, but I don't think this is actually necessary with most syntax highlighting.

I've also wanted to store some regions persistently, for linked editing. We might like to use the same mechanism for both persistent and local regions. Syntax highlight regions should not go to the server, but linked edited regions should. Other users' cursors could also be implemented as regions. Whenever you edit text, it can update the position of the other regions. I'm not sure, though, if this is compatible with the differential synchronization architecture.
