### ISSUE TITLE
Collaborative editing

### ISSUE THREAD

**Issue by morgandixon** [invisible-college/emo#12]
Would be super-cool.

**Comment by toomim** [comment]
Yeah, baby!

**Comment by tkriplean** [comment]
I'm playing The Cure to celebrate

Michael Toomim wrote:

**Comment by morgandixon** [comment]
The logo of emo should be some black side swept bangs.

[image: Inline image 1]

On Thu, Feb 25, 2016 at 5:11 PM, Travis Kriplean notifications@github.com
wrote:

> I'm playing The Cure to celebrate
> 
> Michael Toomim wrote:
> 
> > Yeah, baby!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/invisible-college/emo/issues/12#issuecomment-189062912
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/invisible-college/emo/issues/12#issuecomment-189063686
> .

## 

Morgan Dixon
Computer Science & Engineering
University of Washington
morgandixon.net
